#Generated Form Function

function GenerateForm {

########################################################################

# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.8.0

# Generated On: 7/3/2011 11:35 AM

# Generated By: sean.kearney

########################################################################

#region Import the Assemblies

[reflection.assembly]::loadwithpartialname(“System.Windows.Forms”) | Out-Null

[reflection.assembly]::loadwithpartialname(“System.Drawing”) | Out-Null

#endregion

#region Generated Form Objects

$Gui = New-Object System.Windows.Forms.Form

$UnlockAccountButton = New-Object System.Windows.Forms.Button

$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState

#endregion Generated Form Objects

#———————————————-

#Generated Event Script Blocks

#———————————————-

#Provide Custom Code for events specified in PrimalForms.

$handler_UnlockAccountButton_Click=

{

echo "PWSH-GUI 1.0"

}

$OnLoadForm_StateCorrection=

{#Correct the initial state of the form to prevent the .Net maximized form issue

$Gui.WindowState = $InitialFormWindowState

}

#———————————————-

#region Generated Form Code

$Gui.Text = “PowerShell GUI”

$Gui.Name = “Gui”

$HelpDeskForm.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Size = New-Object System.Drawing.Size

$System_Drawing_Size.Width = 265

$System_Drawing_Size.Height = 55

$Gui.ClientSize = $System_Drawing_Size

$UnlockAccountButton.TabIndex = 0

$UnlockAccountButton.Name = “UnlockAccountButton”

$System_Drawing_Size = New-Object System.Drawing.Size

$System_Drawing_Size.Width = 240

$System_Drawing_Size.Height = 23

$UnlockAccountButton.Size = $System_Drawing_Size

$UnlockAccountButton.UseVisualStyleBackColor = $True

$UnlockAccountButton.Text = “Run script”

$System_Drawing_Point = New-Object System.Drawing.Point

$System_Drawing_Point.X = 13

$System_Drawing_Point.Y = 13

$UnlockAccountButton.Location = $System_Drawing_Point

$UnlockAccountButton.DataBindings.DefaultDataSourceUpdateMode = 0

$UnlockAccountButton.add_Click($handler_UnlockAccountButton_Click)

$Gui.Controls.Add($UnlockAccountButton)

#endregion Generated Form Code

#Save the initial state of the form

$InitialFormWindowState = $Gui.WindowState

#Init the OnLoad event to correct the initial state of the form

$Gui.add_Load($OnLoadForm_StateCorrection)

#Show the Form

$script = $Gui.ShowDialog()| Read-Host 'script:'

} #End Function

#Call the Function
pwsh $script
echo 'Script finished.'
GenerateForm
